services:
  frontend:
    image: ayoubameur/aybhub-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: ayoubameur/aybhub-backend
    ports:
      - "5000:3000"
    env_file:
      - ./Server/.env
    restart: always
